In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
import nltk
import string
import re
from sklearn.feature_extraction.text import TfidfVectorizer
data=pd.read_csv("emails.csv")
data.head(10)

                                                text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1
5  Subject: great nnews  hello , welcome to medzo...     1
6  Subject: here ' s a hot play in motion  homela...     1
7  Subject: save your money buy getting this thin...     1
8  Subject: undeliverable : home based business f...     1
9  Subject: save your money buy getting this thin...     1

In [2]:
data['spam'].value_counts()

0    4360
1    1368
Name: spam, dtype: int64

In [3]:
stopwords=nltk.corpus.stopwords.words('english')
ps=nltk.PorterStemmer()
def count_punc(text):
    count=sum(1 for i in text if i in string.punctuation)
    return round(count/(len(text)-text.count(" ")),3)*100
data['body_len']=data['text'].apply(lambda x:len(x)-x.count(" "))
data['punct']=data['text'].apply(lambda x:count_punc(x))
def clean_text(text):
    text = "".join([word.lower() for word in text if word not in string.punctuation])
    tokens = re.split('\W+', text)
    text = [ps.stem(word) for word in tokens if word not in stopwords]
    return text

In [4]:
from sklearn.model_selection import train_test_split
X=data[['text','body_len','punct']]
Y=data['spam']
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.4,random_state=42)

In [5]:
vect=TfidfVectorizer(analyzer=clean_text)
vect_fit=vect.fit(x_train['text'])
tf_train=vect.transform(x_train['text'])
tf_test=vect.transform(x_test['text'])
tf_train_vect=pd.concat([x_train[['body_len','punct']].reset_index(drop=True),pd.DataFrame(tf_train.toarray())],axis=1)
tf_test_vect=pd.concat([x_test[['body_len','punct']].reset_index(drop=True),pd.DataFrame(tf_test.toarray())],axis=1)
tf_train_vect.head()

,body_len,punct,0,1,2,3,4,5,6,7,...,22771,22772,22773,22774,22775,22776,22777,22778,22779,22780
0,364,5.2,0.000000,0.0,0.083283,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,90,5.6,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,514,7.6,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1702,10.0,0.015309,0.0,0.179637,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,365,2.7,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
alg=LogisticRegression()
alg.fit(tf_train_vect,y_train)
alg.score(tf_train_vect,y_train)
b=alg.predict(tf_test_vect)
count1=0
count0=1
for i in b:
    if i==1:
        count1+=1
    else:
        count0+=1

C:\Users\ADMIN\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [7]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
cm=confusion_matrix(y_test,b)
print(cm)
print(accuracy_score(y_test,b))
print(classification_report(y_test,b))

[[1706    7]
 [ 101  478]]
0.9528795811518325
              precision    recall  f1-score   support

           0       0.94      1.00      0.97      1713
           1       0.99      0.83      0.90       579

    accuracy                           0.95      2292
   macro avg       0.96      0.91      0.93      2292
weighted avg       0.95      0.95      0.95      2292

In [8]:
import pickle 
import joblib
joblib.dump(alg,'pickle.pkl')

['pickle.pkl']